/**
 * RecommendedActions - displays the list of recommended security actions
 *                      and downloadable report buttons.
 *
 * Props:
 *   dark    {boolean} - theme flag
 *   actions {string[]} - array of action strings from API
 *   result  {object}  - full result object (for report download)
 */

function downloadTxt(result) {
  const lines = [
    "===================================================",
    "       EMAIL PHISHING ANALYSIS REPORT",
    "===================================================",
    `Scan ID      : ${result.scan_id}`,
    `Scanned At   : ${new Date(result.scanned_at).toLocaleString()}`,
    `Risk Score   : ${result.risk_score} / 100`,
    `Severity     : ${result.severity}`,
    "---------------------------------------------------",
    "THREAT INDICATORS:",
    ...result.reasons.map((r) => `  [!] ${r.message}`),
    "---------------------------------------------------",
    "URLS FOUND:",
    ...result.urls_found.map((u) => `  ${u.safe ? "[SAFE]  " : "[DANGER]"} ${u.url}`),
    "---------------------------------------------------",
    "RECOMMENDED ACTIONS:",
    ...result.recommended_action.map((a) => `  • ${a}`),
    "===================================================",
    "Generated by Email Phishing Analyzer",
  ];
  const blob = new Blob([lines.join("\n")], { type: "text/plain" });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement("a");
  a.href     = url;
  a.download = `phishing-report-${result.scan_id}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

function downloadJson(result) {
  const blob = new Blob([JSON.stringify(result, null, 2)], { type: "application/json" });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement("a");
  a.href     = url;
  a.download = `phishing-report-${result.scan_id}.json`;
  a.click();
  URL.revokeObjectURL(url);
}

export default function RecommendedActions({ dark, actions, result }) {
  const btnBase = {
    fontFamily: "'Space Mono', monospace",
    fontSize: "0.78rem",
    fontWeight: 700,
    padding: "0.65rem 1.2rem",
    borderRadius: 10,
    cursor: "pointer",
    letterSpacing: 1,
    transition: "background 0.2s",
    display: "flex",
    alignItems: "center",
    gap: "0.45rem",
  };

  return (
    <div
      style={{
        background: dark ? "rgba(15,23,42,0.95)" : "rgba(248,250,252,0.95)",
        border: `1px solid ${dark ? "#1e3a5f" : "#cbd5e1"}`,
        borderRadius: 16,
        padding: "1.75rem",
        display: "flex",
        flexDirection: "column",
        gap: "1.25rem",
      }}
    >
      {/* Recommended actions list */}
      <div>
        <div style={{
          fontFamily: "'Space Mono', monospace",
          fontWeight: 700,
          fontSize: "0.75rem",
          letterSpacing: 2,
          color: dark ? "#38bdf8" : "#0369a1",
          marginBottom: "0.9rem",
          textTransform: "uppercase",
        }}>
          🛡 Recommended Actions
        </div>
        <div style={{ display: "flex", flexDirection: "column", gap: "0.5rem" }}>
          {actions.map((a, i) => (
            <div
              key={i}
              style={{
                display: "flex",
                alignItems: "flex-start",
                gap: "0.7rem",
                fontFamily: "'Space Mono', monospace",
                fontSize: "0.8rem",
                color: dark ? "#e2e8f0" : "#1e293b",
                padding: "0.6rem 0.9rem",
                background: dark ? "rgba(56,189,248,0.05)" : "rgba(3,105,161,0.04)",
                borderRadius: 8,
                borderLeft: "3px solid #38bdf8",
              }}
            >
              <span style={{ color: "#38bdf8", fontWeight: 700, flexShrink: 0 }}>→</span>
              {a}
            </div>
          ))}
        </div>
      </div>

      {/* Download buttons */}
      {result && (
        <div style={{ display: "flex", gap: "0.75rem", flexWrap: "wrap" }}>
          <button
            onClick={() => downloadTxt(result)}
            style={{
              ...btnBase,
              border: "1px solid #38bdf8",
              background: "rgba(56,189,248,0.1)",
              color: "#38bdf8",
            }}
            onMouseEnter={(e) => (e.currentTarget.style.background = "rgba(56,189,248,0.2)")}
            onMouseLeave={(e) => (e.currentTarget.style.background = "rgba(56,189,248,0.1)")}
          >
            ⬇ Report (.txt)
          </button>
          <button
            onClick={() => downloadJson(result)}
            style={{
              ...btnBase,
              border: "1px solid #818cf8",
              background: "rgba(129,140,248,0.1)",
              color: "#818cf8",
            }}
            onMouseEnter={(e) => (e.currentTarget.style.background = "rgba(129,140,248,0.2)")}
            onMouseLeave={(e) => (e.currentTarget.style.background = "rgba(129,140,248,0.1)")}
          >
            ⬇ Report (.json)
          </button>
        </div>
      )}
    </div>
  );
}
